spring.application.name=serratec_flix

#Porta do servidor
server.port=8080

#Conexao com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/serratec_flix
spring.datasource.username=postgres
spring.datasource.password=1234

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true

auth.jwt.secret=EAssim_Que_Minha_Senha_Sera_EAssim_Que_Sera_Autenticado
auth.jwt.expiration-milliseg=7200000
# 2 horas de duração

# Definição para leitura do arquivo .sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always